name: receipt hub admin deploy

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: receipt hub admin dev deploy
        if: github.ref == 'refs/heads/dev'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_PASSWORD }}
          script: |
            cd /home/ubuntu/receipt-hub-team/admin-panel
            git pull
            npm i
            pm2 restart dev-admin
